crt/misc/imaxdiv.c: Fix prototype of `lldiv()`.
This function shall return the struct `lldiv_t`, which used to be
`long long` mistakenly. Although this function is never used throughout
this file, the follow warning was observed when compiling this file:

imaxdiv.c:31:1: warning: 'lldiv' alias between functions of
incompatible types 'ldiv_t(long long int,  long long int)' {aka 'struct
_ldiv_t(long long int,  long long int)'} and 'imaxdiv_t(intmax_t,
intmax_t)' {aka 'struct <anonymous>(long long int,  long long int)'}
[-Wattribute-alias]

This patch fixes the return type hence eliminates the warning.

Signed-off-by: Liu Hao <lh_mouse@126.com>